# Generated by Django 4.0.2 on 2022-02-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staffName', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('staffContactNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
