# Generated by Django 3.2.12 on 2022-03-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=685088, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patientsymptom',
            name='Symptoms',
            field=models.ForeignKey(default=1, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.symptoms'),
        ),
    ]
