# Generated by Django 4.0.2 on 2022-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=789048, unique=True, verbose_name='Case Number'),
        ),
    ]
