# Generated by Django 4.0.2 on 2022-03-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bedId', models.AutoField(max_length=24, primary_key=True, serialize=False)),
                ('bedNumber', models.CharField(max_length=5)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
