# Generated by Django 3.2.12 on 2022-03-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=691782, unique=True, verbose_name='Case Number'),
        ),
    ]
