# Generated by Django 4.0.2 on 2022-03-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staffName',
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffId',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffLastName',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffMiddleName',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffPassword',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffPhoto',
            field=models.ImageField(default=None, upload_to='staffImages'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffUserName',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_leave', 'On_leave')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
