# Generated by Django 4.0.3 on 2022-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patient_casenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='code',
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=807217, unique=True, verbose_name='Case Number'),
        ),
    ]
