# Generated by Django 3.2.12 on 2022-03-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=124292, unique=True, verbose_name='Case Number'),
        ),
    ]
