# Generated by Django 4.0.2 on 2022-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_staff_staffname_staff_gender_staff_staffid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffPhoto',
            field=models.ImageField(upload_to='staffImages'),
        ),
    ]
