# Generated by Django 4.0.3 on 2022-03-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=289243, unique=True, verbose_name='Case Number'),
        ),
    ]
