# Generated by Django 3.2.12 on 2022-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220308_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=480716, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
