# Generated by Django 4.0.3 on 2022-04-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_doctor_code_remove_staff_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='code',
            field=models.CharField(default='000000', max_length=16),
        ),
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(default='000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=119266, unique=True, verbose_name='Case Number'),
        ),
    ]
