# Generated by Django 3.2.12 on 2022-03-07 06:33

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_patient_casenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=24, verbose_name='Patient Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.IntegerField(unique=True, validators=[home.models.validate_phoneNumber], verbose_name='Phone Number')),
                ('patientRelativeNumber', models.IntegerField(validators=[home.models.validate_phoneNumber], verbose_name="Relative's Phone number")),
                ('patientRelativeName', models.CharField(max_length=24, verbose_name="Relative's name")),
                ('reason', models.CharField(max_length=250, verbose_name='Reason')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=897088, unique=True, verbose_name='Case Number'),
        ),
    ]
