# Generated by Django 3.2.12 on 2022-03-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220308_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patientEmail',
            field=models.EmailField(default='abc@abc.com', max_length=254, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=789608, unique=True, verbose_name='Case Number'),
        ),
    ]
