# Generated by Django 4.0.2 on 2022-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_staff_staffphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffPassword',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
