# Generated by Django 3.2.12 on 2022-03-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_patient_casenumber'),
        ('home', '0005_auto_20220307_1203'),
    ]

    operations = [
    ]
