<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-08 14:09
=======
# Generated by Django 3.2.12 on 2022-03-08 06:00
>>>>>>> 06183cb6cb6d7f75285958a70e8ab6cf8aaeccc6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('home', '0006_merge_20220307_1804'),
=======
        ('home', '0006_auto_20220308_1129'),
>>>>>>> 06183cb6cb6d7f75285958a70e8ab6cf8aaeccc6
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
<<<<<<< HEAD
            field=models.IntegerField(default=943134, unique=True, verbose_name='Case Number'),
=======
            field=models.IntegerField(default=648102, unique=True, verbose_name='Case Number'),
>>>>>>> 06183cb6cb6d7f75285958a70e8ab6cf8aaeccc6
        ),
    ]
