# Generated by Django 4.0.3 on 2022-03-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_staff_staffpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedId',
            field=models.AutoField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
