# Generated by Django 3.2.12 on 2022-03-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220308_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=648102, unique=True, verbose_name='Case Number'),
        ),
    ]
