# Generated by Django 3.2.12 on 2022-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=948286, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Id'),
        ),
    ]
