# Generated by Django 3.2.5 on 2022-03-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_bed_bedid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('specializationId', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=24)),
                ('doctorUsername', models.CharField(max_length=15)),
                ('doctorPass', models.CharField(max_length=100)),
                ('doctorContact', models.IntegerField()),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.specialization')),
            ],
        ),
    ]
