# Generated by Django 3.2.12 on 2022-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220308_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='caseNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=896539, unique=True, verbose_name='Case Number'),
        ),
    ]
