# Generated by Django 4.0.2 on 2022-04-01 11:16

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_contactus_contactno_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='contactNo',
            field=models.IntegerField(null=True, validators=[home.models.validate_phoneNumber], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=244456, unique=True, verbose_name='Case Number'),
        ),
    ]
