# Generated by Django 3.2.12 on 2022-03-10 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220308_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialization',
            new_name='Specialization',
        ),
        migrations.AddField(
            model_name='appointment',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedNumber',
            field=models.CharField(max_length=5, verbose_name='Bed Number'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='occupied',
            field=models.BooleanField(default=False, verbose_name='Occupied'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorContact',
            field=models.IntegerField(verbose_name='Doctor Contact'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorName',
            field=models.CharField(max_length=24, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorPass',
            field=models.CharField(max_length=100, verbose_name='Doctor Password'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorUsername',
            field=models.CharField(max_length=15, verbose_name='Doctor Username'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=455807, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=64, verbose_name='Specialization'),
        ),
    ]
