# Generated by Django 4.0.3 on 2022-03-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_doctor_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_Id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_Name', models.CharField(max_length=50)),
                ('equipment_Quantity', models.IntegerField()),
                ('equipment_Assigned', models.IntegerField()),
                ('equipment_Usable', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oxygen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_Total', models.IntegerField(help_text=' Days &')),
                ('oxygen_Total_Hour', models.TimeField(help_text=' Hours of Total Oxygen')),
                ('oxygen_Used', models.IntegerField(help_text=' Days &')),
                ('oxygen_Used_Hour', models.TimeField(help_text=' Hours of Oxygen Used')),
                ('oxygen_Remaining', models.IntegerField(help_text=' Days &')),
                ('oxygen_Remaining_Hour', models.TimeField(help_text=' Hours of Oxygen Remaining')),
            ],
        ),
    ]
