# Generated by Django 3.2.12 on 2022-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220310_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=148813, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
