# Generated by Django 3.2.12 on 2022-03-04 10:45

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_equipment_oxygen'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=24, unique=True, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('caseNumber', models.IntegerField(default=255570, unique=True, verbose_name='Case Number')),
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=24, verbose_name='Patient Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.IntegerField(unique=True, validators=[home.models.validate_phoneNumber], verbose_name='Phone Number')),
                ('patientRelativeNumber', models.IntegerField(validators=[home.models.validate_phoneNumber], verbose_name="Relative's Phone number")),
                ('patientRelativeName', models.CharField(max_length=24, verbose_name="Relative's name")),
                ('line1', models.CharField(max_length=250, verbose_name='Address line1')),
                ('line2', models.CharField(max_length=250, verbose_name='Address line2')),
                ('pincode', models.IntegerField(validators=[home.models.validate_pincode], verbose_name='Pincode')),
                ('previousHistory', models.CharField(max_length=250, verbose_name='Previous history')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('doctorNotes', models.CharField(blank=True, default=None, max_length=250, verbose_name='Doctor Notes')),
                ('doctorLastVisited', models.DateField(blank=True, default=None, verbose_name='Doctor last visited on')),
                ('patientStatus', models.CharField(choices=[('pn', 'pending'), ('cr', 'critical'), ('rc', 'recovering'), ('rcd', 'recovered'), ('dc', 'deceased')], default='pn', max_length=3, verbose_name='Patient Status')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=24, unique=True, verbose_name='State Name')),
            ],
        ),
        migrations.CreateModel(
            name='Symptoms',
            fields=[
                ('symptomsId', models.AutoField(primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=24, unique=True, verbose_name='Symptoms')),
                ('active', models.BooleanField(verbose_name='Active')),
            ],
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symptoms', models.OneToOneField(limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.symptoms')),
                ('patientName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='', verbose_name='Document')),
                ('patientName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='bedNumber',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.bed'),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctorName',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='stateName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.state'),
        ),
    ]
