# Generated by Django 3.2.5 on 2022-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220304_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=456150, unique=True, verbose_name='Case Number'),
        ),
    ]
