<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-03-04 21:34
=======
# Generated by Django 3.2.5 on 2022-03-04 11:14
>>>>>>> 9c7c3238a71b8a8ae456e490263a14a9aa764c30
=======
# Generated by Django 4.0.3 on 2022-03-04 21:34
>>>>>>> f4a6238de99d908ad2f2e6251ab7e6abe483c26c

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220304_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
<<<<<<< HEAD
<<<<<<< HEAD
            field=models.IntegerField(default=122152, unique=True, verbose_name='Case Number'),
=======
            field=models.IntegerField(default=456150, unique=True, verbose_name='Case Number'),
>>>>>>> 9c7c3238a71b8a8ae456e490263a14a9aa764c30
=======
            field=models.IntegerField(default=122152, unique=True, verbose_name='Case Number'),
>>>>>>> f4a6238de99d908ad2f2e6251ab7e6abe483c26c
        ),
    ]
