# Generated by Django 4.0.3 on 2022-03-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=696324, unique=True, verbose_name='Case Number'),
        ),
    ]
