# Generated by Django 4.0.2 on 2022-03-11 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220310_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='configuration',
            fields=[
                ('configurationId', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=362824, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Time'),
        ),
    ]
