# Generated by Django 4.0.3 on 2022-03-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_configuration_fieldname_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='wardName',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='home.ward'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=716987, unique=True, verbose_name='Case Number'),
        ),
    ]
