# Generated by Django 4.0.3 on 2022-03-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_patient_wardname_alter_patient_casenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='wardName',
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=953136, unique=True, verbose_name='Case Number'),
        ),
    ]
