# Generated by Django 3.2.5 on 2022-03-22 10:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_patient_wardname_alter_patient_casenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('blockId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('fieldname', models.CharField(default=None, max_length=100, unique=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('pageId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('fieldname', models.CharField(default=None, max_length=100, unique=True)),
                ('body', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=813310, unique=True, verbose_name='Case Number'),
        ),
    ]
