# Generated by Django 3.2.5 on 2022-03-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20220322_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=376114, unique=True, verbose_name='Case Number'),
        ),
    ]
