# Generated by Django 3.2.5 on 2022-03-24 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_page_status_alter_patient_casenumber'),
        ('home', '0023_alter_patient_casenumber'),
    ]

    operations = [
    ]
