# Generated by Django 3.2.5 on 2022-03-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20220324_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=737641, unique=True, verbose_name='Case Number'),
        ),
    ]
