# Generated by Django 4.0.2 on 2022-03-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20220324_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('contactId', models.AutoField(primary_key=True, serialize=False)),
                ('contactName', models.CharField(max_length=24, verbose_name='Name')),
                ('contactEmail', models.EmailField(max_length=24, verbose_name='Email')),
                ('contactMsg', models.CharField(max_length=100, verbose_name='Massage')),
                ('replyMsg', models.CharField(max_length=24, null=True, verbose_name='Your Reply')),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=725420, unique=True, verbose_name='Case Number'),
        ),
    ]
