# Generated by Django 3.2.5 on 2022-03-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_contactus_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=364781, unique=True, verbose_name='Case Number'),
        ),
    ]
