# Generated by Django 3.2.5 on 2022-03-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=470439, unique=True, verbose_name='Case Number'),
        ),
    ]
