# Generated by Django 3.2.12 on 2022-03-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220329_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorEmail',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='staffEmail',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=998148, unique=True, verbose_name='Case Number'),
        ),
    ]
