# Generated by Django 3.2.12 on 2022-03-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20220330_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=417438, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Id'),
        ),
    ]
