# Generated by Django 4.0.3 on 2022-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_doctor_doctoremail_staff_staffemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='code',
            field=models.CharField(default='000000', max_length=16),
        ),
        migrations.AddField(
            model_name='staff',
            name='code',
            field=models.CharField(default='000000', max_length=16),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctorEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=856766, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staffEmail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Id'),
        ),
    ]
