# Generated by Django 3.2.12 on 2022-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20220330_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='page',
            name='fieldname',
        ),
        migrations.AddField(
            model_name='page',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=762818, unique=True, verbose_name='Case Number'),
        ),
    ]
