# Generated by Django 3.2.5 on 2022-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20220329_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=801783, unique=True, verbose_name='Case Number'),
        ),
    ]
