# Generated by Django 3.2.5 on 2022-03-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20220329_1117'),
        ('home', '0032_auto_20220330_1404'),
    ]

    operations = [
    ]
