# Generated by Django 3.2.5 on 2022-03-30 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_merge_0029_auto_20220329_1117_0032_auto_20220330_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=156899, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorVisitingTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Doctor Visiting Time'),
        ),
    ]
