# Generated by Django 3.2.5 on 2022-03-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220330_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctorVisitingTime',
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=918860, unique=True, verbose_name='Case Number'),
        ),
    ]
