# Generated by Django 3.2.5 on 2022-03-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20220330_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=947346, unique=True, verbose_name='Case Number'),
        ),
    ]
