# Generated by Django 3.2.5 on 2022-03-30 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_patient_casenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctorVisitingTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Doctor Visiting Time'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=274628, unique=True, verbose_name='Case Number'),
        ),
    ]
