# Generated by Django 3.2.5 on 2022-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20220330_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=493190, unique=True, verbose_name='Case Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctorVisitingTime',
            field=models.DateTimeField(blank=True, default=None, verbose_name='Doctor Visiting Time'),
        ),
    ]
