# Generated by Django 3.2.5 on 2022-03-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20220330_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='fieldname',
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=744665, unique=True, verbose_name='Case Number'),
        ),
    ]
