# Generated by Django 4.0.2 on 2022-03-30 12:15

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20220330_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='replyMsg',
        ),
        migrations.AddField(
            model_name='contactus',
            name='contactNo',
            field=models.IntegerField(null=True, validators=[home.models.validate_phoneNumber], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='contactMsg',
            field=models.CharField(max_length=300, verbose_name='Massage'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='caseNumber',
            field=models.IntegerField(default=933230, unique=True, verbose_name='Case Number'),
        ),
    ]
